name: minecraft-java-launcher
title: Minecraft
version: '21'
summary: Minecraft Launcher
description: |
        "Minecraft Launcher for Minecraft: Java Edition"
confinement: devmode
base: core18

parts:
  minecraft-launcher:
    plugin: python
    python-version: python2
    source: https://launcher.mojang.com/download/Minecraft.tar.gz
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - default-jre
      - libxss1
      - libcurl4

apps:
  minecraft-launcher-ot:
    command: minecraft
